### ISSUE TITLE
Next step

### ISSUE THREAD

**Issue by ahmedessa010** [MrPictYT-art/LibDumper#1]
when i open pubg and put in termux su then
./ue4dumper -l
to get pubg libuE4.so 
i didnt get the lib dumped
i get in storage kdata.dat file (large size) 
what should i do with this file ? thank u

**Comment by MrPictYT-art** [comment]
you're posting the issue in the wrong repository

if you're looking for a tutorial about it then go to :
https://github.com/kp7742/UE4Dumper#how-to-use
